name: Build, Push to ECR & Update Helm Repo

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: [self-hosted, Linux, X64]

    env:
      ECR_REGISTRY: 992878410375.dkr.ecr.ap-south-1.amazonaws.com
      ECR_REPOSITORY: code_dev
      IMAGE_NAME: code_dev
      INFRA_REPO: https://github.com/RohithKamasani112/Infra.git
      HELM_FILE_PATH: Helm_App/my-app/values.yaml
 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate image tag
        id: vars
        run: |
          IMAGE_TAG=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Generated tag: $IMAGE_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag and push image to ECR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Clone Infra repo
        run: |
          git clone https://${{ secrets.HELM_REPO_PAT }}@github.com/RohithKamasani112/Infra.git
          cd Infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update image tag in values.yaml
        run: |
          cd Infra
          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|g" $HELM_FILE_PATH

      - name: Commit and push changes
        run: |
          cd Infra
          git add $HELM_FILE_PATH
          git commit -m "Update image tag to $IMAGE_TAG"
          git push https://${{ secrets.HELM_REPO_PAT }}@github.com/RohithKamasani112/Infra.git HEAD:main
